### ISSUE TITLE
1주차 페어 코드 리뷰

### ISSUE THREAD

**Issue by JJW11111** [yzpocket/spring-mvc-BlogApp#5]
- Restful한 설계를 잘 했나요?
  기능에 따라 잘 했습니다.

- API 명세서에 따른 설계가 잘 되어있나요?
 네 잘 되었습니다. 또한 API 명세서를 작성해야되는 이유를 잘 알게되었습니다.
 
- 예외처리가 미흡한 부분은 없나요?
 선택한 게시물(id로 조회)이 없을때 대한 상황에 대해 예외처리가 없었습니다.

**Comment by citeFred** [comment]
> * Restful한 설계를 잘 했나요?
>   기능에 따라 잘 했습니다.
> * API 명세서에 따른 설계가 잘 되어있나요?
>   네 잘 되었습니다. 또한 API 명세서를 작성해야되는 이유를 잘 알게되었습니다.
> * 예외처리가 미흡한 부분은 없나요?
>   선택한 게시물(id로 조회)이 없을때 대한 상황에 대해 예외처리가 없었습니다.

네 감사합니다 진웅님, 위 내용에 맞추어 예외처리에 대한 부분을 추가적으로 학습하고 적용시켜보도록 하겠습니다.
